### ISSUE TITLE
In tree mode, there exists Stored XSS.

### ISSUE THREAD

**Issue by onemoreflag** [josdejong/jsoneditor#1029]
Insert a poc
https://jsoneditoronline.org/#right=local.xobutu&left=local.pawuqa
![image](https://user-images.githubusercontent.com/48425509/86200572-a91a1e00-bb8f-11ea-992d-8303b71068da.png)
click the Drop-down list box
![image](https://user-images.githubusercontent.com/48425509/86200586-b20aef80-bb8f-11ea-921d-d5d409ab7972.png)
click the input tag
![image](https://user-images.githubusercontent.com/48425509/86200596-b8996700-bb8f-11ea-9748-f0c1026e9091.png)

**Comment by josdejong** [comment]
Thanks a lot for reporting @onemoreflag, this is serious. I've just published a fix. Underlying cause was usage of `innerHTML` here and there in the code base, I've replaced all occurrences or made sure they are being feed with escaped HTML only.

Fixed now in `jsoneditor@9.0.2` and https://jsoneditoronline.org `v5.5.7`.
