### ISSUE TITLE
Slashes are not stripped

### ISSUE THREAD

**Issue by sketchub-official** [josdejong/jsoneditor#1049]
There was "another array json" as string in the json, when i tried to view "another array json" , it was saying syntax error because of those slashes.

![image](https://user-images.githubusercontent.com/61039089/87538062-41002780-c6b9-11ea-8fb3-da47e76ed173.png)

**Comment by josdejong** [comment]
Thanks for reporting @sketchub-official . How can I reproduce your issue exactly? 

When using for example double quotes and other special characters inside a json string, you have to escape them in order to have valid JSON, so I'm not sure if there actually is an issue. The "Tree" editor also does show the "raw" string contents including escaping characters.
