### ISSUE TITLE
Are onSelectionChange and getSelection functional?

### ISSUE THREAD

**Issue by natankeddem** [josdejong/jsoneditor#1097]
Using example "15_selection_api.html" I don't get any text at the bottom stating current selection in tree mode and console calls using getSelection() just return "{start: null, end: null}".  Code mode using the "Text" variant appear to work correctly at first glance.  Am I misunderstanding the usage and expected output here?

**Comment by josdejong** [comment]
All seems to work fine. 

It's important to realize that `onSelectionChange` is only supported in tree mode, and `onTextSelectionChange` only in text/code mode (see description in the docs).

**Comment by natankeddem** [comment]
I see my mistake now. I need to click\drag highlight elements in the tree; it is not enough to just click to select them.  I thought these would follow the node path given just below the main menu bar.

**Comment by josdejong** [comment]
Hm yeah I understand that is confusing :S 

The reason is that onSelectionChange currently reflects what nodes are selected, this selection can be dragged/removed/duplicated. When typing text inside, this selection is empty. I keep this in mind to see if we can do something about this but this will be part of a bigger change in functionality.
