### ISSUE TITLE
How to set a custom jsoneditor-field display text per property? 

### ISSUE THREAD

**Issue by s-a** [josdejong/jsoneditor#1103]
How to set a custom jsoneditor-field (property key) display text per property?

**Comment by josdejong** [comment]
Thanks for your question Stephan. I'm not sure what you mean. Do you mean the `placeholder` text on an empty field?

**Comment by s-a** [comment]
Good morning and thank you very much for your fast response. I mean the blue colored text display in example below.
![image](https://user-images.githubusercontent.com/1270662/92551300-f258af00-f25d-11ea-9eea-6108744be2aa.png)
I am at work to i18n your control to german language and would like to translate the JSON property key display text too to make it even more user friendly. I think I could hack this either via rename source JSON obj prop keys iteself or via some CSS tricks, but this is not a clean solution and I thought there might be a cooler way to achive this with build in function or event handler.

best regards and greetings from germany :)

**Comment by josdejong** [comment]
Nice styling in the screenshot you shared! Greetings from the Netherlands, neighbor 😃.

If I understand you correctly, you have a JSON document with a couple of keys like `"fieldDelimiter"`, and you would like to translate that to say `"Feldtrennzeichen"`?

I think there are two directions:

1. Implement a new feature in JSONEditor making it possible to customize how keys and values are rendered. This is a long time wish, but will require some serious work.
2. Since this is really about data contents and not translatable text of the editor itself, you could translate the keys in your JSON document before loading it into the editor, and afterwards translate it back to English if needed.

**Comment by s-a** [comment]
Ok i understand. Thanks for your support. Just wanted to be sure i did not missed something from the docs. 
Since my solution works I leave it as is until new react version breaks this into 2 parts 😄 .
Wish you a happy and productive week!

**Comment by josdejong** [comment]
👍
