### ISSUE TITLE
the web app seems to be loading indefinitely. 

### ISSUE THREAD

**Issue by narendravardi** [josdejong/jsoneditor#1125]
the web app seems to be loading indefinitely in my local.

In incognito, this is working as expected. Can you please let me know how to fix this? 

Attaching the screenshot.
<img width="1242" alt="Screenshot 2020-10-06 at 8 39 27 PM" src="https://user-images.githubusercontent.com/20625060/95220511-2c44b300-0814-11eb-87e6-3bae56129c01.png">

**Comment by josdejong** [comment]
Thanks for reporting. 

So I guess the application is trying to load a document from your local browser storage (in the url you will see something like `#left=local.mecepa`)? What browser are you using? And is it possible for you to see if there are any errors reported in the JavaScript developer console?

As a workaround, it may be easiest to add a few characters to the the id in the url (like `#left=local.mecepaFOO`), and reload the application: that should directly give an error "Document not found", after which you can click "New" to open a new document.

**Comment by narendravardi** [comment]
I am using Chrome `Version 85.0.4183.121 (Official Build) (64-bit)`

It affected only for few hours. Started working as expected later on. 

The data present in the local was not json if that helps.

**Comment by josdejong** [comment]
Thanks for reporting back, good to hear it resolved itself in the end.

> The data present in the local was not json if that helps.

That definitely gives a clue. I do not know however how this could happen, in case of failing to load a (local) file, an exception is caught and displayed. Let's investigate further if this turns out to happen regularly to users. 

I will close this issue now, please reopen if there are more occurrences of the same issue.
