### ISSUE TITLE
Redirect http -> https 

### ISSUE THREAD

**Issue by Ciberusps** [josdejong/jsoneditor#1146]
White screen on http://jsoneditoronline.org
I think should redirect to http(s)?

**Comment by josdejong** [comment]
Thanks for your question Pavel.

The non SSL version of the website should just work and not give a white screen (I just tried it out, seems to just work).

The unsecured version of the website (HTTP) is available because in some countries the secured version of websites (HTTPS) are blocked. So having an unsecured version available is the only way for the people there to actually be able to use the website.
