### ISSUE TITLE
There's lots of arrow functions so this package actually not supporting IE11

### ISSUE THREAD

**Issue by AntiMoron** [josdejong/jsoneditor#1206]
Screenshots from `node_modules/jsoneditor/jsoneditor.min.js`

![image](https://user-images.githubusercontent.com/6587734/103259969-aed5ac80-49d6-11eb-9442-f0b9e7197aa6.png)

**Comment by AntiMoron** [comment]
@josdejong any fix?

**Comment by josdejong** [comment]
Thanks for reporting @AntiMoron . This is a regression in the latest version, `v9.1.6`. Version `v9.1.5` is still right (not having arrow functions. So a workaround of the time being would be to revert to `v9.1.5`

The cause is probably the upgrade from `webpack@4` to `webpack@5`, used for bundling. Will look into it.

**Comment by josdejong** [comment]
This is fixed now in `v9.1.7`.

Cause was webpack@5 outputting es2015 by default and not es5: https://webpack.js.org/migrate/5/#turn-off-es2015-syntax-in-runtime-code-if-necessary

**Comment by AntiMoron** [comment]
thanks.
