### ISSUE TITLE
The indentation command CTRL + \ does not work for windows 

### ISSUE THREAD

**Issue by tayronemachadozup** [josdejong/jsoneditor#1243]
When trying to use the command CTRL + \ in none of the tested cases it works.

The command was tested in the demonstration project "JSONEditor React advanced demo" and on the page
https://jsoneditoronline.org/#left=local.kohiso&right=local.semoku

**Comment by josdejong** [comment]
I just tested on Windows with Chrome and Firefox on https://jsoneditoronline.org, and the quickkeys are just working. 

The keys only work in code mode though, not in tree mode, can that explain it? If not, can you describe the exact steps you do, in which the quickkeys don't work?

**Comment by tayronemachadozup** [comment]
Ok. I tested it on Windows with Chrome and Firefox again and on Chrome an error happens(https://ibb.co/XjrV1bp) but in Firefox the quick keys worked. I'm also testing it on my application that uses the json editor https://playground.usebeagle.io/ and the quick keys didn't work with Chrome either

**Comment by josdejong** [comment]
The error in your screenshot is just that you try to open a document which is deleted or maybe not available like when opening your browser in incognito mode or so (just like the error says, just click the "click here" to get rid of the error)

I tested your version on https://playground.usebeagle.io/, and those quickkeys just works on Firefox, Chrome. I also tried Safari/macOS, there the quickkeys do not work (Ctrl+Shift+\ is used by the browser itself), so maybe we should look into changing the quickkey to something different.

Can it be that there is some Chrome extension in your browser or something like that? Can you whether the issue is gone in Chrome when opening in incognito mode without any extensions?

**Comment by tayronemachadozup** [comment]
Doing some tests, I found it to be a keyboard layout problem. The quick keys work on the international keyboard, but do not work on the ABNT2 keyboard (the most used standard in Brazil). This is probably a problem in Chrome that does not recognize the two keys as being the same, as in firefox it works.

**Comment by josdejong** [comment]
Ahhh, wow! Thanks for tracing this issue down!

I think the best solution is to change the quickkey to a more regular key, not using a character like `\`.

**Comment by tayronemachadozup** [comment]
I suggest something like Xcode with the quickkey `CTRL + i` or IntelliJ `Ctrl + Alt + L`.

**Comment by josdejong** [comment]
Yeah. We need two combinations. We could do `ctrl+i` for format, and `ctrl+shift+i` for compact.

**Comment by tayronemachadozup** [comment]
Yeah i agree, it's a good idea !

**Comment by josdejong** [comment]
The shortcuts are now changed in `v9.2.0`.
