### ISSUE TITLE
Showing ads almost 25% of the viewport is reduced the quality of the site

### ISSUE THREAD

**Issue by kumaravel95** [josdejong/jsoneditor#1251]
![image](https://user-images.githubusercontent.com/9389944/108823197-1e86a300-75e6-11eb-8f38-74af86bcd468.png)

**Comment by kumaravel95** [comment]
https://jsfiddle.net/ is showing ads in nice way.

1. only **Technical Ads**.
2. Place of the advertisement really good.
3. If the user goes for adblocker, they make change our mind to unblock the ads for their site.

**Comment by Moulde** [comment]
This repository is for the jsoneditor, not the website, so this issue is pretty off-topic.

**Comment by kumaravel95** [comment]
@Moulde, I understood you. Ads display component source code are may not be available in this repo. but I hope, jsoneditoronline.org is owned by @josdejong. I gave the suggestions for the website as per his information in the website.

![image](https://user-images.githubusercontent.com/9389944/108949738-f69d4b00-768a-11eb-8f2a-912abc33c66b.png)

**Comment by josdejong** [comment]
Thanks for your input Kumaravel, this is an interesting topic. This is indeed the best place with feedbacks about JSONEditorOnline (since there is no other place).

I find it difficult to do "right". Currently the served ads have a fixed with of 300px. Whether this is "large" depends on your screen resolution of course. Most of the users do have a high screen resolution for which 300px is fine, but for smaller screen resolutions I agree it is not ideal. For a long time I had a toggle to show 160px ads on screens with a width smaller than 1500px. This turned out to be tricky: when accidentally rendering an 300px ad in a space of 160px, you see only part of the ad, and these kind of violations can get you blacklisted by Google Ads very easily. I think it's a good idea though to have another look at this, it would be more user friendly for the people with a small screen.

As for the ad contents: I chose to not allow sensitive categories, and no movies, no popups, etc. I try to keep it decent.

For me personally, I would love to _not_ have ads on the websites I visit, and instead pay a few bucks (like https://scroll.com/). Still, the easiest way to earn some money on the web is with ads, and I try to get some compensation too for the effort I put in this web application and I have to pay hosting costs somehow. I'm thinking about offering a paid, ad-free version of the web application. What do you think about that?

If https://jsoneditoronline.org would be your website, how would you go about this?

**Comment by kumaravel95** [comment]
I understood the reason for increasing the pixel size to 300px and of-course ads will help to pay at-least hosting costs.

But If you see the statistics, only 22% of users users uses higher resolution worldwide and we should consider to reduce the ads size.
![image](https://user-images.githubusercontent.com/9389944/109459884-a99fe700-7a85-11eb-9340-568013c37b62.png)

If it is my website, I will try below options,
1. Google ads have 160x600px ad banner option. I would choose it for only low resolution devices.
2. www.carbonads.net ads.
3. www.buymeacoffee.com.

**Comment by josdejong** [comment]
Thanks for your inputs.

The average user of JSONEditor Online (typically developers) does have a relatively higher screen resolution, the google analytics of the website shows about 34% of the users have a screen resolution below 1500px (and about 10% of those are _very_ close to the threshold), and more than 50% do have a resolution above it (and the remaining percentages is "other" so could be both). We have to be cautious with conclusions about those stats and generic stats from statcounter: in case of statcounter there is a huge category of "other" which is is about 1/3rd of all... (try if the stats of your screenshot add up to 100% 😉 ). Also it, depends quite a bit how you define "high resolution" (I was counting with 1500px or more, but you're using a higher value I suppose? 1920px?).

Anyway, it's a very good point to see again if I can show 160px ads again on smaller screens 👍

**Comment by kumaravel95** [comment]
Thanks for considering it :)

**Comment by josdejong** [comment]
JSONEditor Online will now show smaller ads for screens below 1580px. It can happen that a half visible large ad is rendered on small screens on, this will be resolved by the ad provider soon.

**Comment by kumaravel95** [comment]
Website looks better with my screen now.
![image](https://user-images.githubusercontent.com/9389944/111021866-22c50580-83c7-11eb-9128-126de044018a.png)

**Comment by josdejong** [comment]
👍

**Comment by kumaravel95** [comment]
@josdejong 

Now again, add pane is got larger size for small screens when compared to previous one.
![image](https://user-images.githubusercontent.com/9389944/162667419-dacc8d09-c7ce-4920-a398-d015dde5388e.png)

also non-technical ads also displaying now

**Comment by josdejong** [comment]
That is interesting. Nothing changed since a year ago, where I changed the dynamic ad size to:

> JSONEditor Online will now show smaller ads for screens below 1580px.

So in short:

- Ads have 300px width on screens with a width >1580px 
- Ads have 160px width on screens with a width <= 1580px

Looking at your screenshots now in more detail, I think you have a regular full HD screen with a width of 1920px, which will indeed show ads of 300px. That makes me wonder how you managed to make this screenshot here: https://github.com/josdejong/jsoneditor/issues/1251#issuecomment-797878270 🤔 

Anyway, is the width on your screen an actual problem? I mean, there is plenty enough space to show the JSON contents in the two editor panels I think? (I often have a regular full HD screen too).

> also non-technical ads also displaying now

That is possible. There should be no ads though of sensitive categories like gambling, dating, pharmacy, etc.

Other question @kumaravel95: I have plans to introduce a subscription model for JSON Editor Online, maybe somewhere coming summer. That would give you an ad-free version of the application, and allow you to login and save your JSON documents privately in the cloud, and maybe share them within a team or so. Would such a subscription model be of interest to you?

**Comment by josdejong** [comment]
Closing due to lack of response. Feel free to re-open if needed
