### ISSUE TITLE
Width is stuck and unable to scale or resize

### ISSUE THREAD

**Issue by drveresh** [josdejong/jsoneditor#1258]
Hi,

The width of the right panel is stuck and unable to use 30% space.  I did try to resize and clear history, cache, etc., but nothing worked.  It needs a basic test case to check the width of two panels after being resized, they supposed to be 45-50% each, else something is wrong.
<img width="1389" alt="jsonwidth" src="https://user-images.githubusercontent.com/3812468/109536297-915eb500-7ae3-11eb-9b36-4ed588223fd1.png">

I hope you fix it asap.  Thanks.

**Comment by josdejong** [comment]
ah, that space is reserved to show ads (you know, to help me pay the bills and make some money out of the work I put in this website). Maybe you have an ad blocker, or there was no ad available at that moment? 

It would be nice to show an explanatory text instead of empty space, I''l look into that.

Related discussion: #1251

**Comment by josdejong** [comment]
This is now solved by showing explanatory text "no ad available".
