### ISSUE TITLE
&nbsp; is getting replaced

### ISSUE THREAD

**Issue by mbeekhuis** [josdejong/jsoneditor#1348]
Hi Jos
I've recognized that all `&nbsp;` are getting replaced with normal spaces in the editor. `&thinsp;`-entities are left untouched. Is this behaviour intentionally?

Thanks
Marc

**Comment by josdejong** [comment]
The editor indeed normalizes white spaces: turns it into an alternating sequence of space ` ` and non-breaking spaces `&nbsp;`. The reason is that multiple spaces are not rendered in the browser. And the other way around: if you enter multiple spaces in an Editable Div in the browser, it will be turned into this same alternating sequence. 

Right now the code doesn't handle other white space characters like `&thinsp;`, it may be a good idea to also normalize those.

See code: https://github.com/josdejong/jsoneditor/blob/develop/src/js/Node.js#L3973-L4015

**Comment by josdejong** [comment]
For reference: #1340 discusses an idea to get better control over the exact characters in the text.

**Comment by mbeekhuis** [comment]
Thank you for your explanations
