### ISSUE TITLE
"null" is changed into null

### ISSUE THREAD

**Issue by Antonio-Ramos-Fernandes** [josdejong/jsoneditor#1396]
Hi, in the Beta version, while using the code off option, when declaring a JSON Schema with type : null, the generated code isn't "type": "null", as it should... The generated code is "type": null...

Any idea on when this will be corrected?

I'm a heavy user of your JSON Editor for some years now and I clearly prefer to work with the Beta version... :-)

Antonio Ramos Fernandes.

**Comment by josdejong** [comment]
Thanks for your feedback Antonio, glad to hear you like the beta version :) 

I'm not entirely sure what you mean: when the JSON schema enum contains `null`, then the generated code should be `null` I would think, not `"null"` (which is a string holding the text `null`). Maybe a minimal example helps to explain?

**Comment by Antonio-Ramos-Fernandes** [comment]
Hi, Jos

According to the JSON Schema specs, a Property Type can be an array of Types…

Being an array, that means that each possible Type is one item of that array, which is coded in JSON as, for example:

“type”: [
	“string”,
	“integer”,
	“null”]

Look at the following Schema example, at the **highlighted** lines:

{
    "$schema": http://json-schema.org/draft-07/schema,
    "$id": http://example.com/example.json,
    "type": "object",
    "description": "The root schema comprises the entire JSON document.",
    "required": [
        "SalesJourneyInstanceId",
        "ActivationProcessRecordHistoricalStatusCode",
        "SalesJourneyType",
        "SalesJourneySubType",
        "SalesJourneyStartTimestamp",
        "SalesJourneyApplicantName",
        "SalesJourneyApplicantFiscalNumber",
        "SalesJourneyApplicantEmail",
        "SalesJourneyApplicantMobilePhoneCountryCode",
        "SalesJourneyApplicantMobilePhoneNumber",
        "SalesJourneyNotificationHandOverTimestamp",
        "SalesJourneyActivationHandOverTimestamp",
        "ActivationProcessStatusCode",
        "ActivationProcessStartTimestamp",
        "ActivationProcessExpirationTimestamp",
        "ActivationProcessLastUpdateTimestamp",
        "ActivationProcessLastUpdateOperatorId"
    ],
    "properties": {
        "SalesJourneyInstanceId": {
            "$id": "#/properties/SalesJourneyInstanceId",
            "description": "An explanation about the purpose of this instance.",
            **"type": [
                "string",
                "null",
                "integer"
            ]**
        },
        "ActivationProcessRecordHistoricalStatusCode": {
            "$id": "#/properties/ActivationProcessRecordHistoricalStatusCode",
            "type": "integer",
            "description": "An explanation about the purpose of this instance."
        },

. . . 

    "additionalProperties": true
}

You may also look at how the non-Beta version behaves, which is ok...

Regards.

**Comment by josdejong** [comment]
Ah, ok I think I understand what you mean: when you want to enter a string containing the text null, like `"null"`, the editor turns this into a value `null` instead of a string as soon as you edit the value. The same holds for strings containing numbers, like the string `"123"` is turned into a numeric value `123`. Is that what you mean?

**Comment by Antonio-Ramos-Fernandes** [comment]
Not quite, Jos...
It's ok that the editor shows the value `null` in the array of `type` values...
When it saves to JSON code, it has to save it as `"null"`...
Check how the non-Beta version works on this matter...
The Beta version should work the same way...

**Comment by josdejong** [comment]
I guess I'm missing something obvious here 🤔 . 

I tried with the following schema, having an enum containing a value `"null"` (string containing the text null):

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Enum test #1396",
  "type": "object",
  "required": [
    "myValueType"
  ],
  "properties": {
    "myValueType": {
      "enum": [
        "string",
        "integer",
        "null"
      ]
    }
  }
}
```
When I create a JSON document using this schema, I create a new key `"myValueType"` and from the enum I select `"null"`. Then I get the following JSON, having `"null"` as value for `"myValueType"`, corresponding exactly with the enum value `"null"`:

```json
{
  "myValueType": "null"
}
```

That is what I would expect. So is that the case for you too? And would you indeed expect `"null"` as value, or `null` (like in the classic JSONEditor)?

**Comment by Antonio-Ramos-Fernandes** [comment]
Hi, Jos, to my understanding, your case above took the view symmetrical to what I'm reporting...
What you state is the expected behavior, concerning the JSON code for expressing JSON Schema, and it's ok...
Let's go through my case  step by step...

1. Editing a JSON Schema with the Beta version, in the left panel, code mode off:
![image](https://user-images.githubusercontent.com/29889043/145202791-cd9c3696-e835-4aeb-a5ce-6057c57ba206.png)
2. Notice the streetType Property and its type array values, with one item with value "string"
3. Let's add the null value to the type array values:
![image](https://user-images.githubusercontent.com/29889043/145203103-30b2a1d3-a5e3-4a3c-908e-71c8ba60ef8b.png)
4.Let's click on the "Copy to the right panel" button, set code to on in the right panel and look at the result:
![image](https://user-images.githubusercontent.com/29889043/145203822-f25fb200-8314-4706-bb7b-b6f8404ac151.png).

As you can see, the null value in the JSON code should be enclosed by "" but it isn't...

If you save the schema directly from the left panel, the same result happens, meaning that the saved JSON file has the null value NOT enclosed by ""...

This situation causes any program that uses a JSON Schema like this, to break...

**Comment by josdejong** [comment]
Ahh, I get it (I think 😉). Thanks for your patience. I was assuming your issue was related to the recently implemented JSON schema enums, but it isn't. It is a more generic case, not even specific for JSON schema but for any JSON document in general.

So what is happening is: if you enter a value, it is always entered as text. The editor automatically determines what the value contains: is it a string, a numeric value, a boolean or null? Depending on that, it creates a string, number, boolean, or null in the JSON document. In the classic editor, there is a way to enforce a value to stay a string (change the type to string). In the new editor, there is currently no way to change that. So right now, it is impossible to create a JSON document like `{"a": "123"}`, `{"b": "true"}` or `{"c": "null"}`, these will be created as `{"a": 123}`, `{"b": true}`, and `{"c": null}` respectively. Well: as a work around, you can get this done in _code_ mode.

I'm still thinking about a suitable solution. I think what makes most sense is to create a new option in the context menu to specify the type of the value ("auto" or "string"), similar to the classic editor. Or maybe we can show a type toggle whilst editing a value, since that is the moment where you want to specify entering either a string or auto type. 

Secondly, there are also ways to make the automatic type smarter: look at siblings in the array to see if all of those are for example strings or not, and in case a JSON schema is defined, see if a type is defined there.

**Comment by Antonio-Ramos-Fernandes** [comment]
Yes, Jos, that's the situation! I'm confident that you'll find a good solution... :-)

Meanwhile, when I need to use the null value, I switch to the classic editor to do just that...

**Comment by josdejong** [comment]
It has been a while, and in the meantime I did build a solution for this issue: you can enforce a value to stay a string via the "Enforce string" option in the dropdown menu of "Edit value", see following screenshot. A value will automatically be marked "Enforce string" when it is a string containing null, a boolean, or a number.

![afbeelding](https://user-images.githubusercontent.com/568626/164259553-55c07205-9afe-4aa8-aeb9-eb6b0fb59038.png)
