### ISSUE TITLE
Security issue flagged by Nexus IQ for mobius1-selectr

### ISSUE THREAD

**Issue by cosmin-dev1** [josdejong/jsoneditor#1470]
When scanning a project that uses the jsoneditor package with Nexus IQ this issue is flagged:
![security-issue-iq](https://user-images.githubusercontent.com/113911645/191024512-57fa4ea9-bf07-4604-a3de-5babb608e9f5.png)

I see that https://github.com/Mobius1/Selectr is no longer in active development.  
Is there a plan to have this package replaced with something that's maintained? 
Is this a known issue? 

Any help would be appreciated,
Regards

**Comment by josdejong** [comment]
Thanks for reporting. I think we can solve this quite easily, since according to the report the most recent non-minified file is safe.

Because of issues with the CommonJS version of the project, I did make a copy of the library into [/src/js/assets/selectr](https://github.com/josdejong/jsoneditor/tree/develop/src/js/assets/selectr), which is still at v2.4.0. I'll copy the latest version into the assets folder, that should solve the issue.

**Comment by josdejong** [comment]
This is fixed now in v9.9.2
