### ISSUE TITLE
Security issue caused by mobius 1-selectr jquery-1.12.0.min js

### ISSUE THREAD

**Issue by evil116** [josdejong/jsoneditor#1637]
<img width="1070" alt="mobius 1-selectr jquery-1 12 0" src="https://github.com/user-attachments/assets/46cd01dd-fdb5-4063-9fc7-6a8a9eeef0f0" />

**Comment by evil116** [comment]
there is vulnerability caused by jquery-1.12.0, do you have plan to fix it?

**Comment by josdejong** [comment]
We're using the latest version of the npm package: [`mobius1-selectr@2.4.13`](https://www.npmjs.com/package/mobius1-selectr). However, it was last published 5 years ago, and the GitHub project has been archived since 2021. 

Note that there is no _actual_ scurity issue here: your report points to the `\docs\...` section of the package, which isn't used by `jsoneditor`. 

It would be good to look into replacing `Selectr` with an alternative solution that is actively maintained. What I will do for now is remove `mobius1-selectr` from `package.json`. We already have a copy of the `selectr.js` code in [/src/js/assets/selectr/](https://github.com/josdejong/jsoneditor/tree/develop/src/js/assets/selectr) because there where some commonjs related issues.

Help replacing the library would be welcome.

**Comment by josdejong** [comment]
Addressed now in `jsoneditor@10.1.2`
