### ISSUE TITLE
change event not triggered by JSONEditor.set()

### ISSUE THREAD

**Issue by wayou** [josdejong/jsoneditor#181]
`change ` event not triggered by `JSONEditor.set()` method.

don't know if this is a bug.

**Comment by josdejong** [comment]
Thanks, this is indeed on purpose. The "change" method is fired when the *user* changes contents. 

Typically, when the user changes the contents, you may want to "save" the changes, for example to some server. But when you load a file from the server and display it in the JSONEditor, you don't want this action to trigger a "save" operation because of this.

I've added some more explanation on this in the docs, see https://github.com/josdejong/jsoneditor/commit/0e192937d8ce8e3e809902e047328728259246f2
