### ISSUE TITLE
icon fonts please? 

### ISSUE THREAD

**Issue by mc007** [josdejong/jsoneditor#188]
Hi,
excellent tool! Thank you! Could you please switch to icon fonts (font-awesome has it all) sometime?  
I can do this with some CSS too but hell, would love to see this out of the box. Here an example of a multi-theme app: http://pearls-media.com:89/index.php?view=smdCall&service=XCOM_Directory_Service.get&path=cm9vdCUzQSUyRiUyRmpzb25fZWRpdG9yX3YzLnBuZw==&callback=asdf&raw=html&attachment=0&send=1&user=21232f297a57a5a743894a0e4a801fc3&sig=55abfbc7e19066c4931937cf145b4c1f72bcc0ea

The other thing, not related but is there a reason you're using a server-side module format (CJS) for a we b-application? I started refactoring all back to normal AMD/Require-JS, also solving your OOP problems via DCL = less size and way better inheritance and no! compile step for the debug-version, etc...

thanks!

**Comment by josdejong** [comment]
Thanks, would be nice to use icon font's indeed, that would make it easy to customize the style. It will require some work though: there aren't similar icons available in font-awesome for [all icons of jsoneditor](http://jsoneditoronline.org/img/jsoneditor-icons.png).

I've used AMD in a couple of projects (including jsoneditor), but it was always a pain. For some reason CommonJS+browserify (or webpack) just works like a charm, and I use this for both front-end and back-end. I know you wouldn't have a compile step with AMD but it's no problem to have a compile step. Debugging is no problem at all.

I also just use npm for package management for both font-end and back-end. And since quite some projects I work on are full stack, it makes life much easier to just use one package manager and one module system. I hope we can unite front-end and back-end development (ES6 modules to the rescue?), see also this blog I wrote recently: [A broader view on isomorphic JavaScript](http://josdejong.com/blog/2015/03/28/a-broader-view-on-isomorphic-javascript/).



I'm not sure what you mean with "OOP problems" and "DCL" in this regard.

**Comment by mc007** [comment]
ah, that was you!  I know your Article "a broader view on isomorphic JavaScript". Nice work! That makes me clear again not to use any of those module formats. It got way too lunatic for my projects (40k+ shared modules) and relying on a compile step makes it plain awful complicated and consumes too much time. But sure, depends on what you're doing with the your code. 

I think since i am already replacing your icons, its no biggy to make that missing icons as SVG and bundle them as font. i will let you know. 

About DCL: https://github.com/uhop/dcl, it could help you to roll out your missing 'internal' API way more easy and clean. I see folks here suffering to get an evented API layer into your 'app' and somehow I am also right now scratching my head to get it. And here we are again: you're using CJS, I am using AMD (at least for a while til I have my own solution), so I can't really contribute, what a pity :-) 

ok, don't bother. Here is btw. the 'fork' : https://github.com/mc007/xide-js/blob/master/json/JSONEditor.js. I assume next week or so it should have all to be 'complete' (internal API, multi-selection, insert templates,...).

**Comment by josdejong** [comment]
ha ha, that first ten lines of code in your [`JSONEditor.js`](https://github.com/mc007/xide-js/blob/master/json/JSONEditor.js#L1-L10) really hurts my eye ;). This require.js syntax is so error prone. Anyway thanks for sharing your code.

> relying on a compile step makes it plain awful complicated and consumes too much time

Bundling a large project can take time. However, there are plenty of solutions like live-reload servers and watchers which only re-bundle the changed parts of your code in milliseconds. 

Until one or two years ago I was - like you - against introducing build steps because that would complicate stuff. But I found myself more and more jumping through all kinds of hoops to prevent needing a build step, and was getting tired of fighting require.js. Since I accepted using a build step and started embracing CommonJS+browserify/webpack, life became *much* easier and I never looked back. Especially for more complicated projects relying on 3th party modules using differing module systems. It just works. Besides that, it becomes a no-brainer to start using ES6 in your code right away using [Babel](https://babeljs.io/), which is just great.

In the end it just boils down to what approach fits your project best. But I see a lot of momentum into one particular direction (with good reason) and it's not AMD...

**Comment by mc007** [comment]
funny you! yeah, agreed, I am also sick of screwing the actual code with module boiler-plates which most of the time make collaboration even impossible. 

Unfortunately I can't do much about til I have my own solution (conditional includes,...modules over websocket, etc...), also all connected team-members would have lots of pain if i come up with build-steps (nogo, sorry). The other problem is that node.js world (gulp/grunt) didn't even learn from past tools (gcc) and bloat your directories with thousands of folders = nogo as well. I tried that once with customers but they were just getting really upset, and I fully agree. There is zero benefit for me as I far I could see.

I am actually working on a real-time extendable [IDE](http://pearls-media.com:89/index.php?view=smdCall&service=XCOM_Directory_Service.get&path=cm9vdCUzQSUyRiUyRmh0bWxfd2FyX3pvbmUucG5n&callback=asdf&raw=html&attachment=0&send=1&user=21232f297a57a5a743894a0e4a801fc3&sig=d6dbd628be36fd8b5c8f8110b9c61d32a15af551) (development & debugging in the browser by the customer) and thats pretty much different from the usual stuff you come along as web-dev. Typically you code stuff for being afterwards minfified and maybe transpiled also; so that you actually don't care about debugging/module compatibility/introspection. In my case none of the module formats really worked so I will go on with custom since its working quite good for me and my mates :-)
Maybe one day there will a good module format, taking care about author and transport format...who knows, at the moment its just tooo jumpy, nothing I can trust in without getting throwing under the bus over and over again :-) And the Zero-Deps policy paid out also very well for me.
amen,g

**Comment by josdejong** [comment]
That's an ambitious project, good luck with it!

Building your own module loader sounds like a bad idea, code written for this loader will be compatible with nothing. I suppose you've looked at initiatives like http://jspm.io/ in this regard? I don't know what you mean with "zero-deps policy" but it sounds like you want to build an isolated monolith living in it's own world? I don't know your project and reasons to go that way, but when I hear these sort of choices all alarm bells start to ring.

The node.js world is used to very fine grained modules and code (and hence many small files). That's a good thing, it gives you a lot of control. Note that this the *development* level. You don't need to lumber your customers with all *development* stuff though! You should just publish/distribute a compact built of your application. The difference between development code and distribution code becomes explicit when you have a build step (!) which for example generates files `./dist/myapp.min.js` and `./dist/myapp.min.css`. All you have to distribute to end users is the `./dist` folder.

**Comment by mc007** [comment]
juicy, will think about, thanks. But finally yes, i dont't need 'others'. Since 86, doing in-house code only is fine to me. Really no need for 'fancy stuff' which imply the box of pandorra to be opened :-)

zero-deps: as it says, no middle man involved like npm, github, packagist,...perfect to me.

**Comment by josdejong** [comment]
ha ha, suffering from the not invented here syndrome? ;) 

I like your attitude to keep things simple. It's very easy to make things overly complicated.

**Comment by mc007** [comment]
if you meant 'not invented yet', then yes. after 6 years 'Dojo' (failed for me) now I just started seeing the light at end of the tunnel, getting old-school ux upgraded to web3+ and beyond : DYI,  nice way to get upgraded your self btw. too, period :-)
g

**Comment by mc007** [comment]
so i toyed with http://jspm.io/ and System.js = nice idea but really looks like "hey we a solution, do you have a problem!?".  What's really awesome are the module transformers at compile-time which enable lots of freedom, if you really need to adopt a module to something else of course...

However, after ending up with a huge mess of dependencies, incompatible build-layers and and large amounts of node_module folders, anoying build-steps making actual work somewhat impossible (the promise was the opposite, though, lol), i think its really easier to wait for the right thing instead. I never understood the ongoing and increasingly mess in webtec. I am reading the w3c specs and follow their status since some years now, nothing really seems clear, even ES6 modules and use strict are far from ready or recommendable; finally back to my actual work , thanks again :-)
