### ISSUE TITLE
Acquiring the JSONEditor instance from the DOM

### ISSUE THREAD

**Issue by danlamanna** [josdejong/jsoneditor#204]
I'm doing some high level integration testing of our application with PhantomJS and would like to be able to use set/get on the JSONEditor instance corresponding to a div created with it.

Is it possible to load a JSONEditor from a selector as it stands?

**Comment by josdejong** [comment]
I guess you can add some id to the container div to find it, and attach the created JSONEditor instance as a data attribute to the container div.

**Comment by danlamanna** [comment]
This works, thanks!

**Comment by rsercano** [comment]
But, JSONEditor.instance() constructor would be a nice to see thing

**Comment by josdejong** [comment]
@rsercano I'm not sure what you mean.

**Comment by rsercano** [comment]
What I mean is, Aceeditor has a feature which is named as `.edit` With that method, you are able to reach aceeditor even it's initialized or not. See below:
`var editor = ace.edit("aceEditor");` This code blocks returns the aceeditor instance which has the ID `aceEditor`.

So, if you consider putting this feature to the jsonEditor, that would be awesome. But as you mentioned setting instance to the `data` attribute work already.

**Comment by josdejong** [comment]
Ah, I get it, you want a function like `JSONEditor.getAllInstances()` which returns you all instances of the editor. Still, if there are multiples instances you have no clue which one is attached to which part of your HTML DOM. And if there is just a single instance, it's very easy to keep a reference somehow yourself, either via a local variable (preferable if you ask me!), a global variable, or by attaching it as a data attribute to the DOM element. 

I don't think this would be a broadly needed feature and it has a code smell if you ask me (having no reference to a component where you have to interact with means something is already wrong).

**Comment by rsercano** [comment]
Actually not for all instances but making a method that takes a `dom id` and returning back `jsoneditor instance` would be awesome. Here's my use-case:

I'm creating tabs for every json document for the user's database. Since then, I needed to set the result only active tab's jsoneditor. And I'm currently reaching this value by data attribute. But the mentioned function would kept my code clear than this method. 

Thanks for your interest by the way.

**Comment by josdejong** [comment]
Passing a DOM id indeed makes more sense. That will indeed make your code a bit cleaner. Thanks for explaining your use case, it could make sense there. I think it depends a bit on the way you program: whether you program from code and keep references in code (and see the DOM as just a view but no "source of truth"), or more the jQuery way where you program from the DOM, attach all kind of stuff to the DOM and use selectors to address things.

Still, I don't think we will not create a function for this unless it turns out to be a much requested feature.

Just for reference, here two utility functions to do what you want:

```js
/**
 * Create a new JSONEditor
 * @param {string | Element} selector  A query selector id like '#myEditor'
 *                                     or a DOM element to use as container
 * @param {Object} [options]
 * @param {Object} [json]
 * @return {JSONEditor} Returns the created JSONEditor
 */
function createJSONEditor (selector, options, json) {
  var container = (typeof selector === 'string')
    ? document.querySelector(selector)
    : selector;

  var editor = new JSONEditor(container, options, json);
  container.jsoneditor =  editor;
  return editor;
}

/**
 * Find a JSONEditor instance from it's container element or id
 * @param {string | Element} selector  A query selector id like '#myEditor'
 *                                     or a DOM element
 * @return {JSONEditor | null} Returns the created JSONEditor, or null otherwise.
 */
function findJSONEditor (selector) {
  var container = (typeof selector === 'string')
      ? document.querySelector(selector)
      : selector;

  return container && container.jsoneditor || null;
}
```

Usage:

```js
var editor = createJSONEditor('#jsoneditor', {...});
var editor = findJSONEditor('#jsoneditor');
```

**Comment by rsercano** [comment]
Thanks for sharing, I will try it as soon as possible !
