### ISSUE TITLE
Calling getText() in change function causes editor to lose focus

### ISSUE THREAD

**Issue by synotic** [josdejong/jsoneditor#286]
I have a test case here: http://codepen.io/synotic/pen/wGqzWa

There are no styles in the pen, so ignore that :). If you try and type in the "Hello World" string, Safari keeps losing focus. Chrome is less bad, but the cursor occasionally goes to the beginning of the field.

Debouncing helps a little bit but doesn't entirely resolve this issue. I'm assuming grabbing the state of the editor on change is a very common use case, so I might be missing something here.

Happy to help debug further.

**Comment by kevinulrich** [comment]
I've pulled my hair out over this as well and while i could finally get it to at least keep the focus, the cursor position was seldom kept. I've resorted to not using the change event at all and having the user get the updated JSON manually by button. Not optimal UX but it works for an internal tool.

While searching I've found this issue, part of which sounds oddly familiar: https://github.com/josdejong/jsoneditor/issues/19 
However, that functionality seems to have been refactored meanwhile and the bug is apparently back?

+1

**Comment by josdejong** [comment]
Thanks, will look into it. 

As a workaround it may work to call `editor.getText()` from inside a `setTimout` with a delay of 0 milliseconds.

**Comment by kevinulrich** [comment]
I've found that calling getText at any point in the code, even outside the change handler will make the editor lose focus.

http://codepen.io/anon/pen/GZvevG

**Comment by josdejong** [comment]
I found the cause of this, this regression was introduced recently in v5.2.0. Will fix it asap.

**Comment by josdejong** [comment]
Fixed it in the `develop` branch. I will do a release tomorrow.

**Comment by josdejong** [comment]
I've released v5.3.0 containing this fix.

**Comment by synotic** [comment]
I updated and it works great. Thanks for fixing this!

**Comment by josdejong** [comment]
good to hear, thanks for the feedback.
