### ISSUE TITLE
Feature request - maintain open/close state after editor.set() is called

### ISSUE THREAD

**Issue by antelopeb** [josdejong/jsoneditor#312]
In the particular use I'm working on, there is a point in the flow where of the user changes a value, it affects all the surrounding values as well. This means that we have to re-render the editor by calling editor.set(newData) to get it changed.

However, once this happens, all open tree points are lost, and the state is set back to default. This can be difficult for the user doing the editing, so if we could save state in-between, that would be great.

**Comment by josdejong** [comment]
Thanks. I think the right solution for this is to implement a `patch` method which allows you to replace small sections of the edited JSON rather than start again. 

This has been discussed already but isn't yet supported, see for example https://github.com/josdejong/jsoneditor/issues/271

**Comment by mnzaki** [comment]
Here's a bit of a hack to maintain expanded/collapsed state with the current version:

```js
let data = { some: { new: 'data' } },
  expansionState = {};

saveExpansionState(editor.node, expansionState);
editor.set(data);
restoreExpansionState(editor.node, expansionState)

function saveExpansionState(node, state) {
  state[node.getPath().join()] = node.expanded;
  if (node.childs) {
    node.childs.forEach(child => saveExpansionState(child, state));
  }
}

function restoreExpansionState(node, state) {
  if (state[node.getPath().join()]) node.expand(false);
  if (node.childs) {
    node.childs.forEach(child => restoreExpansionState(child, state));
  }
}
```

**Comment by josdejong** [comment]
Thanks for sharing @mnzaki .

These things will be supported in v6, which is rebuild completely, but is a lot of work and has slow progress.

**Comment by RobAley** [comment]
@mnzaki thanks, I was looking to do this too and found your solution, which works. However it runs quite slowly on large json docs, I think because you continuously join the path to a string and when restoring state iterate over every node in the tree. It also produces a large data structure as you record the state of all nodes, rather than just those that are expanded.  So for anyone else that needs to do the same, my solution inspired mnzaki's is below. It records just the paths that are expanded and keeps the paths as arrays. On restore, it iterates the list of nodes (which are all the expanded ones) rather than the tree, and findNodeByPath takes arrays as paths so there is no need to do join's to make paths, so should be much quicker in most cases.

```
let data = { some: { new: 'data' } },
state = [];

getNodeState(editor.node, state);
editor.set(data);
restoreNodeState(editor.node, state)

getNodeState = (node, state) => {
  if (node.expanded) { state.push(node.getPath()) };
  if (node.childs) { node.childs.forEach(child => getNodeState(child, state)) };
}

restoreNodeState = (node, state) => {
  state.forEach( path => {
    node.findNodeByPath(path).expand(false)
  })
}
```
hope this helps someone.

**Comment by josdejong** [comment]
Hm I see this issue is still open. 

Since some time we have the `update` method which maintains the state of the nodes. I think we can close this issue.

**Comment by RobAley** [comment]
It does indeed need closing, i should have been more explicit in why i was commenting currently. While update works when you have the same editor open, if you need to copy state to a new editor (in my case to restore the state of an editor in a  new browsing session), you need to save the json, expanded state (as here), getSelection etc. manually and restore in the new session. I just wanted to record my solution here as this is the thread that comes up when searching for such. 
Thanks.

**Comment by josdejong** [comment]
Ah, I get it. Yes that makes sense, thanks for sharing @RobAley.
