### ISSUE TITLE
Issues with Permissionsex (Sponge). Editing the .json file

### ISSUE THREAD

**Issue by TacticalTickler** [josdejong/jsoneditor#330]
I am trying to set up ranks for Pex, but am running into this issue: 

Error: Parse error on line 365:
...p:Owner"         ]       }   }
--------------------^
Expecting '}', ',', got 'EOF'

I am very new to this, sorry if it is a total scrub mistake. I would appreciate all the help I can get to set this up properly. Here is what the .json file looks like now http://pastebin.com/NCfvWUxV

**Comment by josdejong** [comment]
The error says `Expecting '}', ',', got 'EOF'`: it expects a `}` or `,`, but reached the end of the file.

Turns out your JSON is missing an closing bracket `}` at the end. It's hard to spot because the document doesn't have proper indentation.

Note that the document also contains duplicate keys (`user` and `nucleus.message.base`), you will loose them when you format the document or edit it in the tree editor (right panel in the web application).
