### ISSUE TITLE
Website doesn't load properly

### ISSUE THREAD

**Issue by sambernaerdtlamosca** [josdejong/jsoneditor#358]
The website doesn't load properly and is not usable at this moment.

![jsoneditoronlinebug](https://cloud.githubusercontent.com/assets/4170898/22200055/bfcc3350-e15d-11e6-8187-1f5c90f2a36a.PNG)

Browser:
Chrome Version 55.0.2883.87 m

Console output:
```
Document was loaded from Application Cache with manifest https://www.jsoneditoronline.org/cache.manifest
(index):1Application Cache Checking event
https://www.jsoneditoronline.org/app.min.css Failed to load resource: net::ERR_CONNECTION_REFUSED
https://www.jsoneditoronline.org/app.min.js Failed to load resource: net::ERR_CONNECTION_REFUSED
(index):136Uncaught ReferenceError: app is not defined
    at (index):136
(index):171Uncaught ReferenceError: app is not defined
    at (index):171
(index):1Application Cache Error event: Manifest fetch failed (6) https://www.jsoneditoronline.org/cache.manifest
https://www.jsoneditoronline.org/img/logo.png Failed to load resource: net::ERR_CONNECTION_REFUSED
https://www.jsoneditoronline.org/favicon.ico Failed to load resource: net::ERR_CONNECTION_REFUSED
```

**Comment by josdejong** [comment]
Thanks for reporting. 

For faster loading and offline availability the website has been using [HTML5 Application Cache](https://www.html5rocks.com/en/tutorials/appcache/beginner/), which is problematic. I've removed using application cache about a year ago from the application, though there was still the manifest file itself. I've removed that now, can you see whether the issue is resolved after refreshing the page? (or maybe Crtrl+F5 to force a refresh)

If that doesn't work I'm afraid you have to clear the cached files [as described here](http://blog.tcs.de/clear-flush-cache-manifest-file-in-chrome/).

Related: #100
