### ISSUE TITLE
Error saving the document online

### ISSUE THREAD

**Issue by hriziya** [josdejong/jsoneditor#365]
I have tried to use Firefox and chrome.. Getting same error "Failed to save document"  see screenshot. 

Also another issue is, failed to load large json text (approx 50k lines) from url.. failed 8/10 try. Let me know if I can help you with anything. 

Thanks

![image](https://cloud.githubusercontent.com/assets/4135216/22831124/2e22981a-efcf-11e6-9cc7-635a62c0d636.png)
****

**Comment by josdejong** [comment]
Thanks for reporting. Is this issue just with trying to save large files? There is a 1MiB limit but you should get a clear error "Too large" when exceeding this size.

I just tried to load/save some (small) documents and that works fine in Chrome and FF on my computer, so the document service seems to be working fine at least.

**Comment by hriziya** [comment]
Try to load the data from this attached file URL. this is where I am getting both above mentioned issue.
1) Not saving json data 
2) Not able to "Open URL" to load json
 
[url.txt](https://github.com/josdejong/jsoneditor/files/768224/url.txt)

**Comment by josdejong** [comment]
Thanks, I can reproduce the issue with your document. One part of the issue may be that the document is 1.2 MB whilst the allowed limit is 1 MB - The application should give a neat "Too large" error in that case though. One other thing I noticed when trying to open the url via "Open URL" is that it took almost 30 seconds, which may have triggered some timeouts or something internally. Again, the application should give a clear timeout error in that case.

**Comment by hriziya** [comment]
Ohok.. Is there any chance I can increase the timeout myself or you guys set it so I can at the least view json data online. 

I can understand the limit of saving data limit of 1MB.  thats fine if it does not work in my case. but loading data is something I used to use regularly :) 

I will wait till you publish this fixes to production.  Thank you!

**Comment by josdejong** [comment]
I've enlarged the timeout from 30 sec to 120 sec, that should solve your immediate issue. Note that another solution would be to simply download the file to your disk, and then load it from disk into the JSON Editor.

Just for clarity: the 1MB limit is only for storing files in the cloud, not for loading documents from disk or url.

Your request take in the order of 20 seconds, so it did not need to trigger this timeout. Reason that it did is because the JSONEditor first tries to load the url directly via the browser, but after ~20s that results in a Cross-domain error. Then the browser tries to load the url via a proxy server which again takes ~20s, more than 30 seconds and hence triggering the timeout.

**Comment by hriziya** [comment]
Okay Thanks a lot.

**Comment by domgarvir** [comment]
Helo,
I've been trying to work with a file that is a little bit above 2M size. 
It loads correctly and I can work with it no problem, but I get a Netwok error when I tried to save it back to my disk (I'm not trying to save onlie).
Is that problem because the file is too big ,or is it possible to work with big files as long as I save back to my local disk? And if that is the case.... could you help my with the network error problem?

Thanks in advance!

**Comment by josdejong** [comment]
@domgarvir Saving a document to your disk doesn't use network, it creates a data url which is then saved to disk. Can you share the document so I can reproduce your issue? On which browser are you trying?

**Comment by domgarvir** [comment]
@josdejong So it seems that the problem was in the browser (chromium), since it worked fine in firefox.
Thanks for the fast answer!

**Comment by josdejong** [comment]
hm. Maybe some limitations in the size of a data url in Chrome then?...

**Comment by hriziya** [comment]
Yes, Chrome has the limitation of 2MB in URL size
[Here is reported bug](https://bugs.chromium.org/p/chromium/issues/detail?id=69227)
but no update since many year.

**Comment by josdejong** [comment]
ah, indeed. That's a very old bug, doesn't look like it will be resolved anytime soon.

Maybe there is a way to detect that saving failed, so the application can at least show the user an error message.

**Comment by kumarmuthaiah** [comment]
How to save file to disk? Please provide code. Thanks! Also icon is not coming when I put svg file in web root/scripts/img folder.

**Comment by kumarmuthaiah** [comment]
scripts folder also contains jsoneditor js and css files

**Comment by kumarmuthaiah** [comment]
Saved file is very big. Thanks!

**Comment by josdejong** [comment]
@kumarmuthaiah I'm not sure what you mean. Can you elaborate?

There is an example on how to load/save from disk here: https://github.com/josdejong/jsoneditor/blob/master/examples/04_load_and_save.html

Saving files larger than 2MB to disk gives an issue in Chrome as reported above.
