### ISSUE TITLE
Long values are modified on formating!

### ISSUE THREAD

**Issue by suketupatel116** [josdejong/jsoneditor#404]
Editor doesn't format 18 digit values.

**Comment by josdejong** [comment]
Thanks for bringing this up again. I already prepared a solution though it's not yet integrated, see 231. I will mark this issue as duplicate.

Note that numbers with 16+ digits can't be handled by front-end (JS) applications in general, since the number format has ~16 digits (it's a regular double float).

**Comment by suketupatel116** [comment]
Thank you @josdejong
