### ISSUE TITLE
Error when onChange + sortObjectKeys in options

### ISSUE THREAD

**Issue by javiermatos** [josdejong/jsoneditor#420]
Hi, I have been trying your project to integrate into django admin forms and it works fine.

The issue I have is that when I use sortObjectKeys, then I get the following error:

```
Error in onChange callback:  TypeError: Cannot read property 'get' of undefined
    at Object.onChange ((index):167)
    at n.h._onChange (jsoneditor.js:8823)
    at n.h._onAction (jsoneditor.js:8807)
    at n.sort (jsoneditor.js:14939)
    at n.setValue (jsoneditor.js:12345)
    at new n (jsoneditor.js:12047)
    at n.h.set (jsoneditor.js:8607)
    at n.setMode (jsoneditor.js:305)
    at n._create (jsoneditor.js:219)
    at new n (jsoneditor.js:182)
```

And here is my javascript:

```
var container = document.getElementById("jsoneditor_{{ name }}");
var options = {
    mode: 'tree',
    search: false,
    onChange: function () {
        var json = editor.get();
        document.getElementById("id_{{ name }}").value=JSON.stringify(json);
    },
    schema: {{ schema|safe }},
    sortObjectKeys: true,
};
var editor = new JSONEditor(container, options);
editor.set({{ data|safe }});
editor.expandAll();
```

**Comment by josdejong** [comment]
Thanks for reporting. 

The reason for this is that when using `sortObjectKeys: true`, the object properties will be sorted on construction of the editor, emitting an `onChange` event before the instance is assigned to the variable `var editor`. I think this is desired behavior (you *do* want to get an `onChange` event since there is actually a change occurring). Maybe we should pass the editor as an argument to the `onChange` callback.

To solve this, I guess that inside `onChange`, you will have to check whether `editor !== undefined` before calling `editor.get()`, and after `var editor = ...`, invoke the `onChange` function yourself to be up to date.
