### ISSUE TITLE
i can't change mode when the value is empty string

### ISSUE THREAD

**Issue by zyc017** [josdejong/jsoneditor#449]
i use the jsonEditor in my react project with defaultvalue is empty string ,when i want to change mode from code to tree, it's failed ,does anybody know why ?

**Comment by josdejong** [comment]
How can I reproduce your issue?

**Comment by zyc017** [comment]
i just create a editor by code like this
`var options = {
        modes: ['code', 'tree'],
        mode: 'code',
        ace: ace,
        onChange: this.handleJsonEditorChange,
        onError:(e) => {
          console.log(e)
        }
      };
var editor = new jsoneditor(container,options);
`
then i can't change the mode while the value is empty

**Comment by josdejong** [comment]
Ah, now I get what you mean. 

When the `code` mode contains text which is not invalid JSON, like being completely empty or containing just half an object like `{"a": `, it cannot switch to `tree` mode because there is no valid JSON object. In that case you will have to display the JSON parse error thrown via `onError` to the user, so the user can fix the JSON first.

**Comment by zyc017** [comment]
ok,i get it ,thank you

**Comment by josdejong** [comment]
:+1:
