### ISSUE TITLE
How to put json code on JSONEditor?

### ISSUE THREAD

**Issue by ganduras** [josdejong/jsoneditor#578]
So I want to create an function (onclick) and set an json inside
the code is :
`{
  "values_setter": {
    "value1": "",
    "value2": "",
  }
}`
I tried to set textarea via jquery but isn't working

**Comment by josdejong** [comment]
I'm not sure what you mean. 

The JSONEditor has two methods `set`, `setText`, `update`, and `updateText` to change the contents of the editor (see docs).

**Comment by ganduras** [comment]
fixed

**Comment by shubhendumadhukar** [comment]
@josdejong I have multiple forms on my page which help prepare a final JSON document and I am using `set` and `refresh` on each submit to update the jsoneditor with the prepared document. Updation works great, however, the changes seem to reflect only when I click on the editor. Is this an expected behaviour? Or can I do something differently?

**Comment by josdejong** [comment]
When programmatically updating the contents of JSONEditor via `.update` or `.set`, it should be immediately be reflected in the rendered contents. It should not be needed to click somewhere in the editor or so.

**Comment by mathemaudio** [comment]
Same story here - updates only when I click it. Is there any internal function that has to happen, some "render" that is kind of called in .update, but probably not always? Can I call it directly?
It happens when I click some other buttons on page, call ".uptate()" while json editor is not in focus.

**Comment by mathemaudio** [comment]
(`.set()` works though... `update` requires a click)

**Comment by josdejong** [comment]
A click shouldn't be needed.

Can you create a minimal example demonstrating the issue?
