### ISSUE TITLE
Tree View - Cursor position not maintained when switching browser tabs

### ISSUE THREAD

**Issue by mjrudowsky** [josdejong/jsoneditor#586]
In the tree view, if I click in the middle of a editable value (key or value) the cursor is positioned where I click. But if I then switch to another browser tab and return, the field is still selected, but the cursor is positioned at the beginning of field I was editing (rather than the position it was when I left).

The code view does not exhibit this problem. The cursor position remains consistent with where I left it.

**Comment by josdejong** [comment]
Thanks for reporting, I can reproduce this this issue.

Will look into it soon.

**Comment by josdejong** [comment]
Finally found the time to look into this issue. Turned out the `onblur` event is fired when switching tabs, and `onblur` the editor escapes the contents of the selected field (ie. replace a return with an escaped `\n` for example). Updating the value caused the caret position to be reset. That's not an issue when actually moving away from the field (blur), but an unfortunate side effect when switching tabs. 

Fixed now by only updating the HTML value when the escaped contents actually changed.

**Comment by josdejong** [comment]
(not yet published)

**Comment by josdejong** [comment]
Fixed now in `v7.0.0`
