### ISSUE TITLE
Implement onValidationError option and a public validate API method

### ISSUE THREAD

**Issue by josdejong** [josdejong/jsoneditor#612]
It would be nice to have a callback function and a method to run/listen for validation errors. This can be used for example to check whether a document is valid before submitting it, or to render validation errors on a different or more prominent place in a web application.

We should think about how this API should look exactly: think about the how to treat both JSON parse errors, JSON Schema validation errors, and custom validation errors.

Followup from discussion here: https://github.com/josdejong/jsoneditor/pull/560#issuecomment-445551510

**Comment by josdejong** [comment]
If anyone is interested in implementing this feature please let me know!

**Comment by optimalisatie** [comment]
We will have a look into it but I am not certain yet that we can provide a solution on short term. 

For anyone interested, the following quick fix is what we are currently using. It requires to load [ajv](https://github.com/epoberezkin/ajv) seperately from json-editor.

```javascript
// load ajv (JSON schema validator)
var AJV = new window.Ajv({
    allErrors: true,
    verbose: true
});

// add a JSON schema to ajv
// schemaSrc = JSON schema object
function add_schema(name, schemaSrc) {
    AJV.addSchema(schemaSrc, name);
    return AJV.getSchema(name).schema;
}

// validate json against schema
function validate_schema(name, json) {
    return AJV.validate(name, json) || AJV.errorsText(); // ajv can return more details, the .errorsText() method is a easy shortcut that serves any error(s)
}

// onChange event in JSON editor options
new JSONEditor('container', {
    /* ... */
    onChange: function() {

        try {
            var json = critical_json_editor.get();
        } catch (e) {
            return;
        }

        var errors = validate_schema(name, json);
        if (typeof errors === 'text') { /* process json errors */ }
    }
}
```

The disadvantage of the solution is that AJV will run 2x and requires additional parsing. An `onValidationError` callback would provide better performance.

**Comment by josdejong** [comment]
:+1: thanks for sharing this workaround Jan Jaap.

as a workaround, I think you could also do:

```js
var errors = myJsonEditor.validateSchema(json)
```

instead of setting up AJV yourself. No official API but should work for now as a workaround.

**Comment by tscislo** [comment]
+1 For this feature

**Comment by JohnBDonner** [comment]
@josdejong I don't think it's possible to reference the jsonEditor object in this scenario, since it doesn't seem possible to edit the options after initialization:

```javascript
var jsonEditor = new JSONEditor('container', {
    /* ... */
    onChangeJson: function(json) {
        // `jsonEditor` doesn't exist yet...
        var errors = jsonEditor.validateSchema(json);
        if (typeof errors === 'text') { /* process json errors */ }
    }
}
```

I believe @optimalisatie (and myself) are trying to validate the schema of the JSON from within the `onChange` callback, which is passed to the `options` object _on_ initalization.

At least, in the current docs, I couldn't find a way to reference it otherwise.

**Comment by josdejong** [comment]
@JohnBDonner so in your case you want to display the current validation errors somewhere in a side bar or header or footer? Maybe an a callback method `onChangeValidationErrors(errors)` which triggers with every change in the errors, both when new errors occur but _also_ when errors are resolved again?

**Comment by JohnBDonner** [comment]
Yes, a callback method like `onChangeValidationErrors(errors)` would be helpful.

My use case is I'd like to disable a form button when the JSON is invalid, and enable the button again when it's valid, where the JSON is invalid based on a schema I've passed in.

**Comment by josdejong** [comment]
That makes sense. Thanks for explaining!

**Comment by hcsgzh** [comment]
`onChangeValidationErrors(errors)` would be good. 
I am use `var errors = myJsonEditor.validateSchema(json)` for now.

Thanks @josdejong

**Comment by littlebearbbb** [comment]
when i use myJsonEditor.validateSchema(json), i get a true or false, how i can get the error message

**Comment by josdejong** [comment]
@littlebearbbb you can read that from `myJsonEdtior.validateSchema.errors` in case validation returned false.

**Comment by jackfrankland** [comment]
@josdejong validateSchema is just what I needed, thank you. Please consider adding it to the API documentation, as I spent a long time fiddling around with Ajv when I could have just used this from the start.

**Comment by josdejong** [comment]
Thanks for your feedback @jackfrankland . Using the internal `validateSchema` is a workaround, we should expose a proper method for it instead, since the internals may change in the future.

**Comment by Puneetsharma891** [comment]
Hi Jos,

I am using OnValidation option instead of schema for validation. Is it possible to get errors without using schema.

**Comment by josdejong** [comment]
@Puneetsharma891 I'm not sure what you mean. If you provide your own `onValidate(json)` function, you can simply call the function yourself with the current json and see if it returns errors.

**Comment by piotrkochan** [comment]
@josdejong this is a big hassle, I'm using integrated ajv, just put a schema to the JSONEditor, everything works fine but I can't just get feedback that is json valid or not. To do that I should create my own Ajv instance and then test json against schema... this as twice job to do at is should be done.

**Comment by josdejong** [comment]
I know it's not ideal.

Again: If anyone is interested in implementing this feature please let me know!

**Comment by meirotstein** [comment]
@josdejong I will have a further look but from the first sight it sounds like something like that:

1. Extend the JSONEditor API with an option to provide a callback function
2. Execute the callback function on the internal `validate()` call

Am I missing something here?

**Comment by josdejong** [comment]
@meirotstein thanks! 

Yes I think so, a callback `onValidationError(errors)` and a method `validate()`. 

I think the `onValidationError` callback should fire on any change in the validation errors: both when there are new errors or the errors change, and also when there where errors that are gone now, else you don't get a trigger when the document changes from invalid to valid. What do you think?

**Comment by meirotstein** [comment]
@josdejong I agree. Will add it on the next days hopefully.

**Comment by josdejong** [comment]
Cool!

**Comment by yzhaopost** [comment]
@josdejong I was just wondering if onChangeValidationErrors(errors) callback is available. I have a use case exactly same as @josdejong has. I want to disable/enable a button based on the validation result. Thank you.

**Comment by josdejong** [comment]
@yzhaopost `onValidationError` is not yet implemented.

**Comment by meirotstein** [comment]
@josdejong I was extending the _next days_ a bit; but finally, I found the time to add this PR :smiley:
Better late than ever I guess...

**Comment by josdejong** [comment]
:joy: yeah time flies. Thanks for picking this up Meir!

**Comment by josdejong** [comment]
`onValidationError` is now available in `v7.4.0`. Thanks again Meir!

**Comment by yzhaopost** [comment]
@meirotstein @josdejong Thank you for providing the "onValidationError" callback. This is awesome!
Now I can catch the validation errors and based on this to enable/disable my button. Thank you!

Just one thing I noticed, for example, I have properties "top", "left", and "width" defined as "number" in my schema. 
![image](https://user-images.githubusercontent.com/45929614/70079862-67ee6b00-15ba-11ea-8023-74ba5f5d1adc.png)
In the Tree mode, when I have the "top" field empty or type in a character instead, it will report the error message "should be a number" in Json editor, and at the same time I get the same error message from the callback. Great!
![image](https://user-images.githubusercontent.com/45929614/70080103-ce738900-15ba-11ea-8274-6d041d24f192.png)
![image](https://user-images.githubusercontent.com/45929614/70080288-20b4aa00-15bb-11ea-9d0d-3bef14f5f05e.png)

In the Code or Text mode, if I do the same thing described above (with an empty "top" field), the error shows in Json editor. But the callback gives no error.
![image](https://user-images.githubusercontent.com/45929614/70080640-c8ca7300-15bb-11ea-9a08-ef54baf04465.png)
![image](https://user-images.githubusercontent.com/45929614/70080745-fd3e2f00-15bb-11ea-981e-1e9c6e7e258d.png)

I understand that the above error (in Code and Text mode) is kind of not a real validation error, actually it is a parser error somehow. But, can we still get this error from the callback? I mean it will be great to receive ALL kinds of errors which are showing in the Json editor. In this case, I can disable my button once there is a Json editor reported error (any errors shown in Json editor). 

Thanks again for implementing the "onValidationError" callback!

**Comment by josdejong** [comment]
Ah, that is an interesting point Yong, I have to double check but I suppose that currently only validation errors are reported. It would be useful indeed to also report parse errors. What do you think @meirotstein?

**Comment by meirotstein** [comment]
@josdejong @yzhaopost I'm super excited that this option is useful already!

It is correct, my implementation reports only scheme validation errors (as the name of this option states).
I can extend it to report also in a case of a parsing error, maybe in a second parameter - so it will preserve the different error types and will be backward compatible (for the very early adopters, such as @yzhaopost 😃)

It will be something like that:

```js
onValidationError(schemeErrors, parseErrors)
```
What do you think?

**Comment by josdejong** [comment]
I think most neat would be to extend the current list with `schemaErrors` to also contain parse errors. We can argue that this not a breaking change in the API, only and extension by reporting _more_ errors. The current schema errors already contain a field `type: 'validation'`, so you can already distinguish parse and validation errors.

**Comment by yzhaopost** [comment]
@josdejong @meirotstein I like the idea of extending the current list with schemaErrors to also contain parse errors. Thank you all for implementing this very very useful callback!

**Comment by meirotstein** [comment]
I agree that this is the most cleaner solution, however it is not that backward compatible because if one expect the error array to be empty only on successful validation now it can return also different types of errors - this can break existing behavior.
On the other hand, this is a very new addition, so the probability for this to happen is quite low. so if you prefer to go in this direction I think it also ok

**Comment by josdejong** [comment]
It's a bit of a gray area, you're right. Thanks for being so careful in this regard! 

I say let's go for it and extend the existing list with parse errors.

**Comment by meirotstein** [comment]
@josdejong I have added a new PR with these changes - pls review. thanks!

**Comment by josdejong** [comment]
Nice, I love it!

**Comment by josdejong** [comment]
Parse errors are now also reported via `onValidationError` in v7.5.0. Thanks again Meir!

**Comment by yzhaopost** [comment]
@josdejong @meirotstein Thank you! I updated to the 7.5.0 and I can see the parse error reported via onValidationError.
But, I did have another issue. Here is my onValidationError. I want to enable/disable a button based on the validation result. 
![image](https://user-images.githubusercontent.com/45929614/70481567-d4280d80-1a97-11ea-9f21-c43fbc76ca59.png)

In Code mode, when I generate a Parse error, I always receive a cross origin error and system crashed:
![image](https://user-images.githubusercontent.com/45929614/70482144-91673500-1a99-11ea-98ef-e78c8acdd0ef.png)

If it is a Validation error, it works great. No any issues, and I could disable the button.

I searched and react Docs suggest to add crossorigin attribute to <script> tags. Since I npm installed JsonEditor, do you have any suggestion about how to include this crossorigin? 

Thank you very much for your help.

**Comment by meirotstein** [comment]
@yzhaopost I'm not that familiar with React, but according to their [doc page](https://reactjs.org/docs/cross-origin-errors.html) it might be a mask for the real parse error.
If you use webpack maybe try the suggestion that on the doc page.

Other than that it is very hard to answer without knowing the exact implementation...

**Comment by yzhaopost** [comment]
@meirotstein thank you for your prompt reply. 
In my case, I get errors array from `onValidationError` including both validation and parse errors (thank you!). 

When there is an error (does not matter validation/parse error) I will set the state `this.setState({ btnDisabled: true })`. The purpose is to disable a button (I will use this button to send the Json file which I am editing in JsonEditor to another module for further handling). 

Since the state changed (`btnDisbaled` is set to true), it will re-render the components including the button and the JsonEditor. At this time, it crashes (cross origin issue) when rending the JsonEditor with an existing parse error. If I do not re-render the component, everything is fine. But, I could not disable the button. 
![image](https://user-images.githubusercontent.com/45929614/70547472-c9b45500-1b25-11ea-9241-9e4e0a93c343.png)

If the error is a validation error, the JsonEditor can be **re-rendered successfully** (with validation errors). 
![image](https://user-images.githubusercontent.com/45929614/70546728-a89f3480-1b24-11ea-9068-a97dda01dcee.png)

**_Looks like re-rendering JsonEditor with a Json file which has a parse error caused this problem_**. Since my project was created using create react app, I could not access to the webpack and can not try the suggestion.  

Here is my `render( )`
![image](https://user-images.githubusercontent.com/45929614/70549627-60364580-1b29-11ea-9f78-6eb66f802048.png)

Here is my `onValidationError`
![image](https://user-images.githubusercontent.com/45929614/70549787-a68ba480-1b29-11ea-844f-b43dd93b7b99.png)

@josdejong @meirotstein Is it possible to re-render JsonEditor with a Json file which has parse error? Thank you very much for your kind help.

**Comment by josdejong** [comment]
> Now it is working. Everything looks good. 

Thanks for your feedback Yong! Enjoy.

**Comment by tafelito** [comment]
I'm trying to use the `onValidationError` callback but I noticed 2 things. 
The callback is fired when calling `jsoneditor.set(json)` the first time as opposed to `onChangeJSON` that's only called after it has been initialized, and is also called after `onChangeJSON`, so there is no way to know inside the `onChange` if the json is valid or not

Basically I want to know when the json changes if it's valid according to the schema. I tried calling the `validateSchema` and validate methods but the `validateSchema` always returns false and the validate does not exists

Is there any other way to know if the json is valid or not?

**Comment by josdejong** [comment]
The callbacks `onChange` and `onChangeJSON` are indeed only fired when the user makes a change, not when new contents are loaded via `jsoneditor.set(json)`.

> Basically I want to know when the json changes if it's valid according to the schema. I tried calling the validateSchema and validate methods but the validateSchema always returns false and the validate does not exists

This is the API of [ajv](https://github.com/ajv-validator/ajv#getting-started). I do not know why it was created like this, but first you execute `editor.validateSchema(json)`, and when that returns false it means there are errors, and in that case you can read the errors via `editor.validateSchema.errors`.

> Is there any other way to know if the json is valid or not?

 There are various ways, like the one above. The most controlled way would be to simply create your own ajv instance (which you can pass as option to JSONEditor too). That way you can always run `ajv.validate` whenever you want to, and have JSONEditor use the exact same.

**Comment by tafelito** [comment]
Thanks @josdejong for the response
I was missing the the json arg when calling the  `editor.validateSchema(json)`  that's why it was always returning false. 

It'd would be great to have some sort of `blur` event of the editor, so the validation doesn't run on every change 

as a side note, validateSchema function is missing from the type declaration

**Comment by josdejong** [comment]
> as a side note, validateSchema function is missing from the type declaration

It's not official API (see my comment: https://github.com/josdejong/jsoneditor/issues/612#issuecomment-449568275). This issue is there to create an actual, proper API for this :)

> It'd would be great to have some sort of blur event of the editor, so the validation doesn't run on every change

You can take various approaches here, like debouncing changes so you do validate less often. Actually, there are methods `onFocus(event)` and `onBlur(event)`, see [test/test_focus_tracker.html](https://github.com/josdejong/jsoneditor/blob/develop/test/test_focus_tracker.html), but I see they are missing in the documentation. I will add them to the docs.

**Comment by tafelito** [comment]
> It's not official API (see my comment: #612 (comment)). This issue is there to create an actual, proper API for this :)

👍

> You can take various approaches here, like debouncing changes so you do validate less often. Actually, there are methods onFocus(event) and onBlur(event), see test/test_focus_tracker.html, but I see they are missing in the documentation. I will add them to the docs.

that's what I ended up doing but I for my use case the onBlur is even better. Thanks for pointing that out. To get the value should i just use the editor.get? The onBlur doesn't seem to return the json value

**Comment by josdejong** [comment]
>  To get the value should i just use the editor.get? The onBlur doesn't seem to return the json value

Yes that's correct.
