### ISSUE TITLE
Is there a way to auto-set the value type for certain field names? 

### ISSUE THREAD

**Issue by kabachello** [josdejong/jsoneditor#618]
Hi! First of all, thank you so much for this brilliant editor! 

I use it to let users edit a deeply nested JSON with lot's of complex dependencies between fields. Currently I use an AJAX-autocomplete for fields and values to help users fill things in correctly. 

The type of the values (array, object, scalar, etc) depends on the path to that value. To push the editing comfort even further, I'm looking for a way to auto-select the value type based on the path: e.g. if the path is root > x > y, the value should be an array, where as for root > x > z it is a scalar. I could even go further and auto-insert complex templates, if there was a way to do stuff like this. 

Unfortunately there is no schema for my JSON and it seems barely possible to create one in reasonable time.

So far I thought of the following possibilities:

- some sort of end-of-field-editing event. This would be easy, if the event would contain the path to the field. 
- an onAutocompleteSelected-event would be OK too, if the path would be known or at least the selected value. 

In both cases I could get() the JSON, modify it and set it back... 

Unfortunately, I can't see any of those in the API events. Did I miss something? Or is there another possibility maybe?

Many thanks in advance!

**Comment by josdejong** [comment]
@kabachello I guess what comes closest is simply listening for changes (`onChangeJSON`), and calling `update` with the adjusted JSON object to change the value to the right type. Have you tried whether something like that works?

**Comment by kabachello** [comment]
@josdejong Thanks for the idea. I've tried it, but ran into two problems :

1. How to determine which field has changed? I need this info because I want to modify it's value. 
2. The event is being fired for every change (I.e. every character typed) while I am only interested in the last character before leaving the field. 

I came up with another idea: I will try to hook to the blur event, which I expect to work with editable divs. Is there an easy way to get the path-array, if I know, which div represents the field, I am invertersted in?

**Comment by josdejong** [comment]
Ah, sounds like listening for `onBlur` makes sense then. I'm not sure if that's easy, the onblur is used internally, it may be that propagation is stopped. 

There is a way to find the internal `Node` from a DOM element, see `Node.getNodeFromTarget`. Disclaimer: this is all internal API which may change in future versions without notice, breaking your solution if you're depending on it:

https://github.com/josdejong/jsoneditor/blob/72ab51002c27381474522d4090de5ed0ad3c237f/src/js/Node.js#L3837-L3852

It is indeed quite inefficient to listen for every change, though that may not be an issue in practice when you're not dealing with large JSON documents. To figure out _what_ exactly changed after an `onChangeJSON` event you could use a json-diff library. This would be a solution direction I would prefer myself since it neatly decouples user interaction from the logic to adjust JSON after a change. There are quite some different ways a user can change a field and you would need to keep track on quite some different user interactions to keep everything consistent I guess (enter text, copy/paste text, duplicate a node, remove a node, undo/redo, ...). Anyway, just my 2 cents.

**Comment by kabachello** [comment]
@josdejong thanks for your help. I managed to get things working now. I ended up using the blur event of node field elements, got the node with the method above and used the Node.setValue() to auto-set a template. As a bonus I use the API to set the focus to the next empty field. I know, there is probably no guarantee for the internal API to remain unchanged, but I'll have to live with that. Getting the whole JSON, changing it and setting it back seems a lot more complicated. And there would be no solution for the focus feature.
