### ISSUE TITLE
Getting read of the annoying white border in Chrome.

### ISSUE THREAD

**Issue by felipecarrillo100** [josdejong/jsoneditor#637]
Some of you have probably noticed that when using jsoneditor in chrome the blue menu on top seems to have a white line on the left at 100% zoom. In Firefox it looks just fine. 

This was very annoying for me.  I tried to modify the CSS but it was very hard to find the solution. Finally googling on the internet I found a fix.  This seems something internal to the Chrome rendering of the html/css.  The solution is to use "thin" instead of "1px"  at the div.jsoneditor border.  Hopefully you can add this to your css for future releases. 

Great job by the way,  I use your jsoneditor in several projects. So far the best I have found.

div.jsoneditor {
    border: thin solid #000000;
}

**Comment by josdejong** [comment]
@felipecarrillo100 thanks for your input. I'm not sure what white border you mean. Here is a screenshot of example01.html in Chrome:

![image](https://user-images.githubusercontent.com/568626/51443897-701a2080-1cf0-11e9-83a5-d4d1ad405260.png)

When/where is this white border visible?

**Comment by josdejong** [comment]
Hm. I'm running `Version 71.0.3578.98 (Official Build) (64-bit)` too...

can you attach your image again? Seems to to work when sending a reply via email.

**Comment by felipecarrillo100** [comment]
![image](https://user-images.githubusercontent.com/16829954/51483838-4c131980-1d9a-11e9-803b-39462abd26fd.png)

**Comment by felipecarrillo100** [comment]
It seems related to the size of the browser window.   Only for some widths you have it.

I was able to reproduce it in your website https://jsoneditoronline.org/

Make the zoom level 100%  and then resize the window horizontally until you see the white line appear.

Best regards
![image](https://user-images.githubusercontent.com/16829954/51484403-bd070100-1d9b-11e9-889b-e0e9a2e12388.png)

**Comment by josdejong** [comment]
Thanks for the extra explanation @felipecarrillo100, that helped. I managed to reproduce your issue on https://jsoneditoronline.org when zetting the zoom level to 125% and then either moving the bar between the two panels or resizing the browser width. When zoomed at 100% I couldn't reproduce it.

I have done a bit of testing and can't find an easy fix either. It looks a bit like a bug in the Chrome browser, there is nothing special going on: 
- there is a div with a width of for example 380px, 
- the div contains a div with 100% width, no margin/padding a 1px border
- this div contains the menu div with width 100%, 0 margin, border-box and 2px padding

The issue seems not to occur when removing the border.

**Comment by felipecarrillo100** [comment]
This  is easy to fix with the workaround proposed. Use the CSS I provided at my initial message. 
Instead of "1px" use "thin" in the border of the jsoneditor div.

div.jsoneditor {
  border: thin solid #000000;
}

**Comment by josdejong** [comment]
:+1: 

I've changed the border width from `1px` to `thin`, which indeed solves the issue in Chrome. I still saw the issue popping up when zoomed in on IE11 but not anymore on Chrome.

**Comment by josdejong** [comment]
Thanks @felipecarrillo100 for figuring this out!
