### ISSUE TITLE
Object viewer doesn't correctly display escaped characters

### ISSUE THREAD

**Issue by JebediahSpringfield** [josdejong/jsoneditor#655]
If I enter a value containing quotes

{
  "value": "\"\""
}

It shows the backslashes as part of the value:  eg.  value : \\"\\"  when it should only display "".

![image](https://user-images.githubusercontent.com/29605934/52738647-129a8c00-2f9d-11e9-9995-7b89e7a4b096.png)

**Comment by josdejong** [comment]
We can argue whether it's the best solution, but this was done by design. The escape characters are displayed as is in the editor, so you cannot loose any special characters in the browser like `\t` and `\n` which cannot be expressed nicely in a browser. For unicode characters there is an option `escapeUnicode` which determines whether to render the unicodes icon or the code.

**Comment by JebediahSpringfield** [comment]
I see, it's just that I would expect the displayed value to reflect the actual value of the qualifier in question. In my case the escape character is not part of the data, only the double quotes. 
Perhaps an option could be added at the top of the page to modify the behavior of the visualization of escape characters?
    Le mercredi 13 février 2019 à 15:08:42 UTC−5, Jos de Jong <notifications@github.com> a écrit :  
 
 
We can argue whether it's the best solution, but this was done by design. The escape characters are displayed as is in the editor, so you cannot loose any special characters in the browser like \t and \n which cannot be expressed nicely in a browser. For unicode characters there is an option escapeUnicode which determines whether to render the unicodes icon or the code.

**Comment by josdejong** [comment]
> I see, it's just that I would expect the displayed value to reflect the actual value of the qualifier in question.

How would you like to display `\t`, `\r`, and `\n` in the browser then?

**Comment by JebediahSpringfield** [comment]
Good question. Have you ever received feedback about this?
I understand it's useful to display these escaped characters for readability, however, for the case of escaped quotes and escaped backslash, the escape character does not make part of the data.
I was wondering about having a display option to switch between a "Data view" and "Content view".
The "Data view" would display the actual data (as interpreted by a print) whereas the "Content view" would keep the current behavior.
In my specific case the content of the JSON was a regular expression and I was using the editor to verify if the value was actually correct in the display. Since the view shows all the escape charactersit was hard to understand if I was writing a proper expression.
What do you think?
By the way, my compliments for the great work. The fact that your tool is used in many different "Json editor" websites just under a different skin is enough proofthat your tool became a reference on the web. Thank you.

    Le jeudi 14 février 2019 à 14:37:49 UTC−5, Jos de Jong <notifications@github.com> a écrit :  
 
 

I see, it's just that I would expect the displayed value to reflect the actual value of the qualifier in question.


How would you like to display \t, \r, and \n in the browser then?

**Comment by josdejong** [comment]
Thanks for your kind words :)

In the beginning I tried to be smart about this and parse `\n` into `<br/>` and things like that, basically try to achieve a "Content View". But that gave all sorts of difficult cases and didn't work reliable on all different browsers. So I changed it to simply show the data contents, and haven't heard any issues since.

I think the way ahead would be implement hooks to customize how the data is rendered. Like how booleans render a checkbox, and colors render a color picker. But then give full control, also allow replacing the input box with something custom rendered. This was discussed already in an open issue somewhere.
