### ISSUE TITLE
Duplicating nodes — how to remove "(copy)" ?

### ISSUE THREAD

**Issue by mmiszy** [josdejong/jsoneditor#766]
This commit https://github.com/josdejong/jsoneditor/commit/00baaacaccd802eb19bfc540d87003e7e760e291 introduced a breaking change which is rather important to our team.
Duplicated nodes are now suffixed with " (copy)".
What's the easiest way to disable this behavior?

We obviously don't allow duplicated keys in objects, we just want our users to edit them manually.

**Comment by josdejong** [comment]
This changes was introduced in [`v5.32.2`](https://github.com/josdejong/jsoneditor/blob/develop/HISTORY.md#2019-04-03-version-5322) in order to fix an issue reported in #671. Allowing duplicated nodes caused quite some tricky edge cases and complications in the code having to handle it since duplicate keys cannot be represented in JSON itself. Not allowing duplicate nodes in the first place solves all of this and makes related code way simpler.

It's not possible to go back, quite some logic depends on the keys being unique. What _may_ be possible is hacking into the code such that on duplication, you give the `field` the focus instead of the `value`, and when the field has focus you can change the input text to be the same as the original (without the ` (copy)` suffix). As soon as the field loses focus, it will make the name unique again (adding the ` (copy)` suffix if necessary). Thinking about it, it may be not a bad idea at all to make this the default behaviour when duplicating properties, in that case you normally want to change the key anyway.

**Comment by josdejong** [comment]
See ca6e384e8d9ab552c0f1999fd58a70dd4e3f5f19. Will that address your concern?

**Comment by josdejong** [comment]
Addressed in `v6.3.0`, closing this issue. Feel free to reopen if needed.

**Comment by mmiszy** [comment]
@josdejong that addressed my concerns :) Thank you!

**Comment by josdejong** [comment]
:+1: thanks for letting me know Michal.
