### ISSUE TITLE
How to treat number as a string

### ISSUE THREAD

**Issue by igiton** [josdejong/jsoneditor#770]
I have situation to set 01 02 03 etc as a value in input field.
But the problem is that editor automatically removes leading zeros and I got wrong data 1 2 3 etc.
Is there possibility to set some option that will not remove leading zeros or to pass number as a string? I wouldn't use '01', '02' etc...

**Comment by josdejong** [comment]
Numeric input is indeed parsed into numbers, losing any formatting like leading zeros. If you need to keep this formatting you'll have to provide them as strings instead. You could maybe do a pre- and post-processing step where you replace these values with strings and vice versa.

**Comment by igiton** [comment]
Yes, I implemented pre and post processing. Tnx.

**Comment by josdejong** [comment]
:+1:

**Comment by harandK** [comment]
How can I prevent auto conversion to a numeric value? 

For the creation of the jsoneditor form I fetch the document from the server as a json template with all fields and predefined data types (numeric, string,...). 

Now a numeric input in a string field leads to auto conversion to numeric, which invalidates my data model.

Let's say I have an ID field which is a string field and values like  abcdefg111 or 111111 are valid string inputs.  
But, the 111111 value gets converted to a numeric value. Also including "" ' ' invalidates my data model.

And I don't want to write a validation function, because the template documents are variable.

**Comment by josdejong** [comment]
That is a good question indeed, JSONEditor doesn't have an answer to that right now, except for the manual changing of the type to "String". 

One way could be to utilize type definitions from a JSON Schema. Do you have other ideas?

As a workaround, I think you'll have to post-process your JSON and change number into string where needed.

**Comment by lnaie** [comment]
This seems to work well with json editor:
```
"type": [ "integer", "string" ],
```
More details: https://cswr.github.io/JsonSchema/spec/multiple_types/

**Comment by josdejong** [comment]
Yes indeed, it requires jsoneditor to utilize this knowledge from the JSON Schema after you have edited a value, to determine whether to turn it into a number or a string.
