### ISSUE TITLE
Dependency versions hard locked

### ISSUE THREAD

**Issue by tsilen** [josdejong/jsoneditor#771]
Is there a reason why the dependencies of jsoneditor are hard locked to exact versions instead of allowing minor version updates?

Now e.g. security fixes to the dependencies can't be installed before jsoneditor upgrade's its package.json and releases a new version.

For example mobius1-selectr is currently locked to 2.4.10 in 5.x branch while the fixed version is 2.4.11.

**Comment by josdejong** [comment]
The reason to use fixed dependencies stems from a best-practice establised before `package-lock.json` existed. It is always possible that a dependency update breaks something, even if it is marked as only a bug fix release. So, if you allow non-exact versions, you can suddenly have a broken setup. 

The latest version of JSONEditor uses all the latest versions (see [package.json](https://github.com/josdejong/jsoneditor/blob/develop/package.json#L32), has `mobius1-selectr@2.4.13). We've set up [greenkeeper](https://greenkeeper.io) to be notified automatically when there are dependency updates, Though there will be always some delay between a dependency being updated and a new version of jsoneditor being released.

It could be that it's time to reconsider this best practice of using fixed version numbers. I'm open that. Important for me is to be able to publish a version of JSONEditor that's guaranteed to work and cannot break uncontrollably due to some change in a dependency.
