### ISSUE TITLE
Editor trapping form submit Enter keypress

### ISSUE THREAD

**Issue by rgravina** [josdejong/jsoneditor#85]
When using a json editor inside a html form, it traps the Enter keypress normally used to submit a form. E.g., when pressing Enter inside a text input field. E.g.

![screen shot 2014-01-28 at 1 48 27 pm](https://f.cloud.github.com/assets/19086/2016379/84a3ba2e-87d7-11e3-9660-bc7312346738.png)

The <code>change</code> function is fired, but since it has no arguments, there is no way to handle the event.

Is there any known way around this?

**Comment by nicozimmermann94** [comment]
Can confirm that this bug still exists in current version. I have a simple form with this editor inside. I am not able to submit the form via Enter Key in any input form field.

**Comment by josdejong** [comment]
@nicozimmermann94 thanks for your feedback. Just to be sure: you have the JSONEditor inside a form and you want to press the enter key inside one of the input fields of the JSONEditor to submit the form right?

**Comment by nicozimmermann94** [comment]
Exactly

**Comment by josdejong** [comment]
ahh, thanks. The editor should definitely not influence the behavior of inputs/forms outside it's own container. Thanks for the clear jsfiddle, will fix this bug asap.

**Comment by josdejong** [comment]
I found the reason. Turns out forms have some very special behavior to determine the "submit" action. See my experiments here:

http://jsbin.com/qecepim/edit?html,output

I've given all buttons in the JSONEditor an attribute `type="button"`. That will fix submitting on enter, as long as there is a button or input with `type="submit"` in the form too.

I will do a bug fix release in a few days.

**Comment by josdejong** [comment]
This should be fixed now in `v5.5.10`.

**Comment by nicozimmermann94** [comment]
Thank you very much!
