### ISSUE TITLE
Incorrectly exporting sourcemaps

### ISSUE THREAD

**Issue by bnewcomer** [josdejong/jsoneditor#858]
I am getting a warning from webpack using source-map-loader that it cannot find SourceMap 'uri.all.js.map' in 'jsoneditor/dist'. It looks like jsoneditor is not correctly exporting its source maps.

```
WARNING in <path to node modules>/node_modules/jsoneditor/dist/jsoneditor.js
Module Warning (from <path to node modules>/node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'uri.all.js.map': Error: Can't resolve './uri.all.js.map' in '<path to node modules>/node_modules/jsoneditor/dist'
 @ <path to node modules>/node_modules/jsoneditor/index.js 1:17-45
 ...
```

**Comment by josdejong** [comment]
Thanks for reporting Benjamin.

Looks like the uri.js library (one of the dependencies) has a source mapping (coming from TypeScript I think): https://github.com/garycourt/uri-js/blob/master/dist/esnext/uri.js#L480

I'm not sure how to solve this, strip source map urls from dependencies or so? Or is Webpack supposed to resolve source maps of dependencies into a new source map? Does anyone have an idea?

**Comment by maneetgoyal** [comment]
Getting a similar warning in Google Chrome dev tools while loading the non-minified bundle:

<img width="1040" alt="Screen Shot 2020-04-25 at 2 12 21 PM" src="https://user-images.githubusercontent.com/25290212/80291026-cf8a8b80-86fe-11ea-9a51-b12f6cae80b2.png">


The `JSONEditor` [bundled code](https://cdnjs.cloudflare.com/ajax/libs/jsoneditor/8.6.6/jsoneditor.js) has this line: 
```
//# sourceMappingURL=uri.all.js.map
``` 

Looking at the [Gulp file](https://github.com/josdejong/jsoneditor/blob/develop/gulpfile.js#L99), it seems that only for the **minified** bundle the source map is provided. So that version (`*.min.js`) is coming out OK. If a sourcemap is provided for non-minified version too, it might be replaced properly automatically. If you don't want to provide sourcemap for non-minified bundle, then I don't see anything wrong with stripping `//# sourceMappingURL=uri.all.js.map` as 1 possible solution (disclaimer haven't used Gulp/Webpack much, mostly Rollup).

**Comment by josdejong** [comment]
Thanks for reporting and the suggestions Maneet. 

A totally different solution would be to simply not offer the non-minified version 😃

**Comment by josdejong** [comment]
This issue should be fixed now in `v8.6.7`. Can you give it a try @maneetgoyal?

**Comment by maneetgoyal** [comment]
No more Chrome devtool warnings @josdejong 👍

**Comment by josdejong** [comment]
👍
