### ISSUE TITLE
Why is the toISOString method called when the value is a timestamp

### ISSUE THREAD

**Issue by CodeVam** [josdejong/jsoneditor#872]
When the value is a time stamp, why the toISOString method is called makes me misunderstand the prompt, because it's not my current time zone
`this.dom.date.innerHTML = new Date(value).toISOString();
  this.dom.date.title = new Date(value).toString();`

**Comment by josdejong** [comment]
What the preferred output is, local time or UTC, may differ per application. We could discuss what would be the best default (currently this is UTC). In any case, since the [recently released `v8.0.0`](https://github.com/josdejong/jsoneditor/blob/develop/HISTORY.md#2019-12-11-version-800) you can customize how the date is formatted, see option `timestampFormat`.

**Comment by CodeVam** [comment]
thanks.this is a goog idea.I believe highly configurable will make users like it more

**Comment by CodeVam** [comment]
thanks.this is a goog idea.I believe highly configurable will make users like it more

**Comment by CodeVam** [comment]
thanks.this is a good idea.I believe highly configurable will make users like it more

**Comment by CodeVam** [comment]
thanks.this is a good idea.I believe highly configurable will make users like it more
