### ISSUE TITLE
when I use code mode and json data is initialized to {}, it can not edit

### ISSUE THREAD

**Issue by zhangyanggithub** [josdejong/jsoneditor#913]
I cloned this git repository , and change  the code on jsoneditor/examples/react_demo/src/JSONEditorDemo.js to:
```
import React, {Component} from 'react';

import JSONEditor from 'jsoneditor';
import 'jsoneditor/dist/jsoneditor.css';

import './JSONEditorDemo.css';

export default class JSONEditorDemo extends Component {
  componentDidMount () {
    const options = {
      mode: 'code',
      onValidationError (err) {
        console.log(err);
      },
      onChange: this.onChangeJSON.bind(this)
    };
    this.jsoneditor = new JSONEditor(this.container, options);
  
    this.jsoneditor.set(this.props.json);
  }

  onChangeJSON() {
    try {
      const json = this.jsoneditor.get();
      this.props.onChangeJSON(json);
    } catch (err) {
      console.log(err)
    }
  }

  componentWillUnmount () {
    if (this.jsoneditor) {
      this.jsoneditor.destroy();
    }
  }

  componentDidUpdate() {
    this.jsoneditor.update(this.props.json);
  }

  render() {
    return (
        <div className="jsoneditor-react-container" ref={elem => this.container = elem} />
    );
  }
}

```
bug I cant edit , when keydown the Entry, it will find error on console like:
![image](https://user-images.githubusercontent.com/20579231/75233722-43d6aa80-57f4-11ea-8788-aaa730242877.png)

unless I initialized the json data to object with one or more keys.

**Comment by vitalets** [comment]
I'm getting the same error with the following setup:
```js
    const options = {
      mode: 'code',
      search: false,
      mainMenuBar: false,
      navigationBar: false,
      statusBar: false,
      colorPicker: false,
      onChange: () => this.handleChange(),
  };
```
Devtools shows that array index `endRow` exceeds lines array length:
![image](https://user-images.githubusercontent.com/1473072/75336132-a33bc580-589b-11ea-8e39-6a22d92c33ac.png)

**Comment by josdejong** [comment]
The reason is that when you're using code mode, and you're making changes, the contents of the editor will be temporarily invalid JSON whilst typing. In that case `const json = this.jsoneditor.get()` will throw an error, and the contents of the editor will be out of sync with the state in React.

It is similar to having a a number in your React state, and wanting to change that in an `<input>` field: when a user clears the input field, there is no valid numeric value, and you can't parse this into a valid number to keep your React state in sync with the contents of the input field. 

To solve this, you have to replace working with a JSON object for working with text containing the JSON object. You can use the callback `editor.onChangeText` and update the contents using `editor.updateText`. See the `examples/react_advanced_demo` which does exactly that and this way can handle all different modes.

**Comment by vitalets** [comment]
@josdejong

As you suggested I've used `onChangeText` and `updateText`.
When I make invalid json in editor - everything works.
But if i just press enter to insert newline - I'm getting this error (it still provides **valid** json). 

Example:
I'm having this json:
```json
{
  "text": "text"
}
```
When I insert newline I'm getting:
```json
{
  "text": "text"
  
}
```
This is passed up to react state -> it re-renders editor -> it calls componentDidUpdate where I call `editor.updateText(JSON.stringify(props.json))`. The reason why I need to call `JSON.stringify` is because somewhere in the app I anyway store my value as json (not text).

**Comment by josdejong** [comment]
If you parse the text from the JSONEditor code mode into a JSON object and afterwards stringify that again, any text indentation and formatting like an empty line is gone...

**Comment by vitalets** [comment]
> If you parse the text from the JSONEditor code mode into a JSON object and afterwards stringify that again, any text indentation and formatting like an empty line is gone...

Yes. That's exactly what I mean. 
Is it possible for editor to incapsulate all formatting issues inside and just provide json-in json-out?

**Comment by josdejong** [comment]
There are basically two possibilities if you want to use `code` mode:

1. Controlled component. If you use `code` mode you must keep the document contents as a string in your React state because you can't capture formatted (and invalid) text in a JSON object.
2. Uncontrolled component. Pass the initial document as a JSON object to the editor on creation of the editor, but do not pass updated JSON objects consecutively since it will ruin your text formatting in `code` mode. Listen for changes in the text of the JSONEditor using `onChange` or `onChangeText`, and in the callback try parse the text contents into JSON (`JSON.parse(editor.getText())`. If parsing is successful, pass this to your own internal React state (but don't feed it back into the JSONEditor). If not successful because the entered text is not valid JSON, you may want to show an error to the user or something like that.

**Comment by zhangyanggithub** [comment]
thank you ~ josdejong， I fix the problem with the example of examples/react_advanced_demo. 

But I used a lot of time, this props 'text' can not accept JSON.stringfy({}) directly Seemingly, it only accepts '{}', meanWhile changed text value can not be pass with JSON.parse('{}') when I used  JSONEditorDemo be a Child components.

**Comment by josdejong** [comment]
@zhangyanggithub good to hear you've a working solution now. 

> But I used a lot of time, this props 'text' can not accept JSON.stringfy({}) directly Seemingly, it only accepts '{}', meanWhile changed text value can not be pass with JSON.parse('{}') when I used JSONEditorDemo be a Child components.

I hope you understand the reason for this, I tried to explain it above: if you have JSON text containing indentation and empty lines, and you parse it into JSON and stringify it again, all the text formatting like empty lines and indentation is gone.

**Comment by vitalets** [comment]
> 2\. Uncontrolled component. Pass the initial document as a JSON object to the editor on creation of the editor, but do not pass updated JSON objects consecutively since it will ruin your text formatting in `code` mode. Listen for changes in the text of the JSONEditor using `onChange` or `onChangeText`, and in the callback try parse the text contents into JSON (`JSON.parse(editor.getText())`. If parsing is successful, pass this to your own internal React state (but don't feed it back into the JSONEditor). If not successful because the entered text is not valid JSON, you may want to show an error to the user or something like that.

Thank you! That's the solution I came.
The only issue - at some moment I should anyway update json in editor (some external event in my app while editor is visible). I solved it with following:
```js
  shouldComponentUpdate(nextProps) {
    // update editor json only from outside event
    return JSON.stringify(nextProps.json) !== JSON.stringify(this.tryGetCurrentJson());
  }

  componentDidUpdate() {
    this.jsoneditor.update(this.props.json);
  }

  tryGetCurrentJson() {
    try {
      return this.jsoneditor.get();
    } catch (e) {
      // invalid json
    }
  }
```

**Comment by josdejong** [comment]
Ah, that's a really smart idea comparing the contents in `shouldComponentUpdate` :+1: Thanks for sharing! You could probably also do a deep equal comparison of the JSON contents instead of stringified contents. 

Will close this issue now, glad to hear you have a working solution now.
