### ISSUE TITLE
Custom font color style for nodes fail

### ISSUE THREAD

**Issue by liangzhijian0** [josdejong/jsoneditor#990]
Hi, this jsoneditor component is really too powerful, but I have difficulty in developing custom node colors:

I refer to the example of **20_custom_css_style_for_nodes.html**, but I can only change the background-color, not the color. Even if I add _**!important**_ can't overwrite the **_#1a1a1a_** color attribute set in the original **_div.jsoneditor-field_**/**_div.jsoneditor-value_**.

Is there any other solution? Many thanks!

**Comment by josdejong** [comment]
You have to write a bit more specific CSS, since the colors are defined individually on the fields and values, and not on their parent (where the custom class is attached). I've updated the example you mention to show how to change font color: https://github.com/josdejong/jsoneditor/commit/c2fa821a31e9ceeb4c6763240860aa9f633fb7b9.

**Comment by liangzhijian0** [comment]
Got it, many thanks, can close this issue
